Keeysight/Controllers/GraphNChartController.cs
using Keeysight.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using Syncfusion.Pdf;
using Syncfusion.Pdf.Graphics;
using System.IO;
using Syncfusion.Drawing;
using System.Threading.Tasks;

namespace Keeysight.Controllers
{
    public class GraphNChartController : Controller
    {

        //https://docs.microsoft.com/en-us/ef/core/miscellaneous/configuring-dbcontext
        // This is the dependency injection for DbContext, must be initialised first if u decided to use depency injection 
        /*
        private readonly TestTableContext _context;
        public GraphNChartController(TestTableContext context)
        {
            this._context = context;
        }
        */


        //[Authorize(Roles = "Admin")]
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        // Respond to POST
        [HttpPost]
        public async Task<IActionResult> Add(TestTable model)
        {
            if (ModelState.IsValid)
            {
                //using (_context) <- this is dependency injection
                using (var context=new TestTableContext())
                {
                    TestTable user = new TestTable
                    {

                        Name = model.Name,
                        Id = model.Id
                    };

                    //Only use AddSync So if you use a value generator that might need to access the DB to get new values to assign to new entries, such as the SequenceHiLo generator, then use AddAsync().
                    context.TestTable.Add(user);

                    await context.SaveChangesAsync();

                    return RedirectToAction("Index", "Home");
                }
                
            }
            else
            {
                return RedirectToAction("Error", "Home");

            }
        }

        // Respond to POST
        [HttpPost]
        public async Task<IActionResult> Update(TestTable model)
        {
            if (ModelState.IsValid)
            {
                //using (_context) <- this is dependency injection
                using (var context = new TestTableContext())
                {
                    TestTable user = new TestTable
                    {

                        Name = model.Name,
                        Id = model.Id
                    };

                    context.TestTable.Update(user);
                    context.SaveChanges();
                    await context.SaveChangesAsync();

                    return RedirectToAction("Index", "Home");
                }

            }
            else
            {
                return RedirectToAction("Error", "Home");

            }
        }

        // Respond to POST
        [HttpPost]
        public async Task<IActionResult> Delete(TestTable model)
        {
            if (ModelState.IsValid)
            {
                //using (_context) <- this is dependency injection
                using (var context = new TestTableContext())
                {
                    TestTable user = new TestTable
                    {

                        Id = model.Id
                    };

                    context.TestTable.Remove(user);
                    await context.SaveChangesAsync();

                    return RedirectToAction("Index", "Home");
                }

            }
            else
            {
                return RedirectToAction("Error", "Home");

            }
        }


        [HttpGet]
        public ActionResult CreateDocument()
        {

            //Create a new PDF document
            PdfDocument document = new PdfDocument();

            //Add a page to the document
            PdfPage page = document.Pages.Add();

            //Create PDF graphics for the page
            PdfGraphics graphics = page.Graphics;

            //Set the standard font
            PdfFont font = new PdfStandardFont(PdfFontFamily.Helvetica, 20);

            //Draw the text
            graphics.DrawString("Hello World!!!", font, PdfBrushes.Black, new PointF(0, 0));

            //Saving the PDF to the MemoryStream
            MemoryStream stream = new MemoryStream();

            document.Save(stream);

            //If the position is not set to '0' then the PDF will be empty.
            stream.Position = 0;

            Console.WriteLine("LALA");

            //Download the PDF document in the browser.
            FileStreamResult fileStreamResult = new FileStreamResult(stream, "application/pdf");
            fileStreamResult.FileDownloadName = "Output.pdf";
            return fileStreamResult;

        }
    }
}

Keeysight/Views/GraphNChart/Index.cshtml
@model TestTable

@{
    ViewData["Title"] = "Graph & Chart";
}
@section Chart{
    <!--ChartJs Core Javascript and CSS -->
    <script src="~/lib/chartjs/dist/Chart.bundle.min.js"></script>
    <link rel="stylesheet" href="~/lib/chartjs/dist/Chart.min.css" />

}




<h1>Index</h1>
<div class="row">
    <div class="col-6">
        <canvas id="myChart"></canvas>
    </div>
    <div class="col-6">
        <canvas id="myChart2"></canvas>
    </div>

</div>


<div class="row">
    <div class="col">
        <div class="form-group">
            Label
            <input type="text" id="Label" />
        </div>
        <div class="form-group">
            Value <input type="text" id="Value" />
        </div>
        <input type="button" value="push" onclick="addData()">
    </div>
    <div class="col">
        <input type="button" value="Pop" onclick="removeData()">
    </div>
    <div class="col">
        <input type="button" value="remove first one" onclick="removeFirstOne()">
    </div>
    <div class="col">
        <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                <button class="dropdown-item" type="button" onclick="changeToLine()">Line</button>
                <button class="dropdown-item" type="button" onclick="changeToBar()">Bar</button>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col">
        <form asp-action="Add" method="post">
            <div class="form-group">
                <label asp-for="Id"></label>
                <input asp-for="Id" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
            </div>
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>
</div>

<div class="row">
    <div class="col">
        <form asp-action="Update" method="post">
            <div class="form-group">
                <label asp-for="Id"></label>
                <input asp-for="Id" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
        @{Html.BeginForm("CreateDocument", "GraphNChart", FormMethod.Get);
            {
                <div>
                    <input type="submit" value="Create Document" style="width:150px;height:27px" />
                </div>
            }
            Html.EndForm();
        }
    </div>
</div>

<div class="row">
    <div class="col">
        <form asp-action="Delete" method="post">
            <div class="form-group">
                <label asp-for="Id"></label>
                <input asp-for="Id" class="form-control" />
            </div>
            <button type="submit" class="btn btn-primary">Delete</button>
        </form>
    </div>
</div>

<!--Chart 1-->
<script>
    var ctx = document.getElementById('myChart').getContext('2d');
    var chart = new Chart(ctx, {
        // The type of chart we want to create
        type: 'line',

        // The data for our dataset
        data: {
            labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
            datasets: [{
                label: 'My First dataset',
                backgroundColor: 'rgb(255, 99, 132)',
                borderColor: 'rgb(255, 99, 132)',
                data: [0, 10, 5, 2, 20, 30, 45]
            }]
        },

        // Configuration options go here
        options: {

        }
    });
</script>

<!--Chart 2-->
<script>
    var ctx = document.getElementById('myChart2');
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
            datasets: [{
                label: '# of Votes',
                data: [12, 19, 3, 5, 2, 3],
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });

</script>

<script src="~/js/chart.js"></script>